name: Pylint

on: [push]

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get install libmysqlclient-dev
        pip install pylint flask flask-mysqldb
    - name: Analysing the code with pylint
      run: |
        cd backend
        pylint `ls -R|grep .py$|xargs`
